name: vercel_dart
description: A utility library for writing serverless functions in the Vercel Dart Runtime.
version: 1.0.0
repository: https://github.com/frencojobs/vercel-dart

publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  http: ^0.13.4
  shelf: ^1.2.0

dev_dependencies:
  lint: ^1.7.1
  test: ^1.17.12
